name: GitHub Actions - Variables - Demo
run-name: ${{ github.actor }} is testing out Variables with GitHub Actions 🚀
on: 
  push: 
    paths:
      - '.github/workflows/demo-variables.yml'

env:
  DAY_OF_WEEK: Monday #environment variable for a single workflow
  VERSION: "v0.1.${{ github.run_number }}" #environment variable for a single workflow with an embed default variable (github.run_number)

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_DEVELOPMENT }} #Repository variable
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        env:
          First_Name: Mona
        run: | 
          echo $VERSION
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "${{ vars.LEAVING }} $First_Name!" #"ENVIRONMENT_DEVELOPMENT" environment's variable 