name: GitHub Actions - Variables - Demo
run-name: ${{ github.actor }} is testing out Variables with GitHub Actions 🚀
on: 
  push: 
    paths:
      - '.github/workflows/demo-variables.yml'

env:
  DAY_OF_WEEK: Monday #environment variable for a single workflow
  VERSION: "v0.1.${{ github.run_number }}" #environment variable for a single workflow with an embed default variable (github.run_number)

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    outputs:
          output1: ${{ steps.step1.outputs.test }}

    steps:
      - name: "Say Hello Mona it's Monday"
        id: step1
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        env:
          First_Name: Mona
        run: | 
          echo $VERSION
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "test=${{ env.First_name }}!" >> "$GITHUB_OUTPUT"

  leaving_job:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_DEVELOPMENT }} #Repository variable
    needs: greeting_job
    
    steps:
      - env:
          OUTPUT1: ${{needs.greeting_job.outputs.output1}}
        run: |
          echo $VERSION
          echo "${{ vars.LEAVING }} $OUTPUT1" #Environment variable