name: GitHub Actions - Variables - Demo
run-name: ${{ github.actor }} is testing out Variables with GitHub Actions 🚀
on: 
  push: 
    paths:
      - '.github/workflows/demo-variables.yml'

env:
  DAY_OF_WEEK: Monday #environment variable for a single workflow
  VERSION: "/home/runner/work/bsr-azure-01/bsr-azure-01" #environment variable for a single workflow with an embed default variable (github.run_number)

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_DEVELOPMENT }} #Repository variable
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        env:
          First_Name: Mona
        run: | 
          echo $VERSION
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "${{ vars.LEAVING }} $First_Name!" #"ENVIRONMENT_DEVELOPMENT" environment's variable 
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: $VERSION
          path: ${{ env.VERSION }}/data/synapse
