
name: Dockerfile build and push to ACR

on: 
  push: 
    #branches: main
    paths:
      - 'docker/**'
      - '.github/workflows/dev-docker-build.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_DEVELOPMENT }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker/
          push: true
          tags: ghcr.io/${{ github.actor }}/demo:v1