name: Run Azure Login with OpenID Connect
on: 
  push: 
    paths:
      - '.github/workflows/dev-azure-login.yml'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_DEVELOPMENT }}
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd
          
    - name: Add ML extension
      run: az extension add -n ml; az ml -h
