
name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    environment:
      name: uat
    steps:
      -
        name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: bsrdevacr01.azurecr.io
          username: ${{ vars.ACR_SP_APP_ID }}
          password: ${{ secrets.ACR_SP_PASSWORD }}
