
name: Dockerfile build and push to ACR

on: push
    #: branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_DEVELOPMENT }}
        #name: dev
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: bsrdevacr01.azurecr.io
          username: ${{ vars.ACR_SP_APP_ID }}
          password: ${{ secrets.ACR_SP_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker/
          push: true
          tags: bsrdevacr01.azurecr.io/samples/test:v1