name: GitHub Actions - Azure Machine Learning deploy - Demo
run-name: ${{ github.actor }} is testing out Azure Machine Learning deployment with GitHub Actions 🚀
on: 
  push: 
    paths:
      - '.github/workflows/uat-ml-pipeline-deployment.yml'
  workflow_dispatch:  

permissions:
      id-token: write
      contents: read

env:
  artifactDirectory: "release-artifact-folder"
  mlPath: "models/pipelines"

jobs:

  download-release:
    name: 'Latest Release Import to Azure Machine Learning'
    runs-on: windows-latest
    environment: uat

    steps:
    - name: Clean Directory
      continue-on-error: true
      run: rm ${{ env.artifactDirectory }} -r -force -ErrorAction SilentlyContinue      
      
    - name: Download latest release
      uses: robinraju/release-downloader@v1.7
      with:
        latest: true
        fileName: "*.zip"
        out-file-path: ${{ env.artifactDirectory }}
        
    - name: Check downloaded files
      run: dir ; dir ${{ env.artifactDirectory }}

    - name: Unzip Release Artifact
      run: cd ${{ env.artifactDirectory }}; Get-ChildItem -Filter *.zip | Expand-Archive -DestinationPath . -Force 
          
    - name: Iterate over ${{ env.mlPath }}
      run: |
          foreach($folder in Get-ChildItem -path ${{ env.artifactDirectory }}/${{ env.mlPath }} -Directory -Name)
          {
            Get-ChildItem -Path ${{ env.artifactDirectory }}/${{ env.mlPath }}/$folder -Name
            "Only YAML files:"
            @(Get-ChildItem -Path ${{ env.artifactDirectory }}/${{ env.mlPath }}/$folder\*.yml -Name)[0]
          }
